# These are supported funding model platforms

github: # @Zefanya-Dev
patreon: # Replace with a single Patreon username
Vaneza_zefanya_Dev_200907502023: # https://www.instagram.com/fanie__/
bikinbikinhub: # https://www.instagram.com/bikinbikinhub/
