# These are supported funding model platforms

github: # @Zefanya-Dev
community: # KALLA HOSPITALITY
Vaneza_zefanya_Dev_200907502023: # https://www.instagram.com/fanie__/
bikinbikinhub: # https://www.instagram.com/bikinbikinhub/
